#!/bin/sh /etc/rc.common

START=99
STOP=1

USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command sh -c 'cd /root/64key && exec /usr/bin/python3 .'
  procd_set_param respawn
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param pidfile /var/run/64key.pid
  procd_close_instance
}
